version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investment-scripts
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./:/app/data
    restart: 'no'
