version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filter-dividend-champions
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
